version: '2'

# environment:
# - constraint:node==<hostname>

services:  
 crc:
  image: app-docker136.hex.tno.nl:443/pitch/crc:5.3.0.0L
  mac_address: 00:18:8B:0D:4F:0B
  networks:
  - simnet
  
 kml:
  image: app-docker136.hex.tno.nl:443/msaas-nld/kmlserver:pi
  command: -f KMLServer -iconurl http://localhost:8090/kmlserver
  ports:
  - "8090:8080"
  environment:
  - FEDERATIONNAME=ShipSim1
  - PITCH_LRCADAPTER=10.13.0
  networks:
  - simnet
  
 shipsim:
  image: app-docker136.hex.tno.nl:443/msaas-aus/shipsim:pi
  command: -f ShipSim --scalable
  environment:
  - FEDERATIONNAME=ShipSim1
  - PITCH_LRCADAPTER=10.13.0
  networks:
  - simnet

 shipbackground:
  image: app-docker136.hex.tno.nl:443/msaas-aus/shipsim:pi
  command: -f TrafficSim --scalable -background background.json -background-count 10
  environment:
  - FEDERATIONNAME=ShipSim1
  - PITCH_LRCADAPTER=10.13.0
  networks:
  - simnet
  
 webcop:
  image: app-docker136.hex.tno.nl:443/msaas-nld/cesium
  ports:
  - "7777:8080"  
  networks:
  - simnet
  
networks:
 simnet:
  driver: overlay
  ipam:
   config:
   - subnet: 10.13.0.0/24
     gateway: 10.13.0.1
  