version: '2'

services:  
 kml:
  image: app-docker136.hex.tno.nl:443/msaas-nld/kmlserver:pi
  command: -f KMLServer -iconurl http://127.0.0.1:8091/kmlserver
  ports:
  - "8091:8080"
  environment:
  - FEDERATIONNAME=ShipSim2
  - PITCH_LRCADAPTER=10.13.0
  
 shipsim:
  image: app-docker136.hex.tno.nl:443/msaas-aus/shipsim:pi
  command: -f ShipSim --scalable
  environment:
  - FEDERATIONNAME=ShipSim2
  - PITCH_LRCADAPTER=10.13.0
  
 shipbackground:
  image: app-docker136.hex.tno.nl:443/msaas-aus/shipsim:pi
  command: -f TrafficSim --scalable -background background.json -background-count 10
  environment:
  - FEDERATIONNAME=ShipSim2
  - PITCH_LRCADAPTER=10.13.0
  
networks:
 default:
  external:
   name: shipsimexercise1_simnet
  