version: '2'
# This file runs basic services for MSaaS portal including portal web server nginx.
# Before running you should: 
#   - download the portal html code from GitHub in MSaaS-A/codebase/MSaaSPortal,
#   - download the demo compose files from GitHub in MSaaS-A/compose-files/MSaaSPortal
#   - adapt the index.html files to your environment (docker hosts),
#   - in this file adapt the nginx and compose volumes directive to your environment.
#
# On the docker host this file should be started with:
# docker-compose -f msaas-portal.yml up -d 
#
# From a web browser you can then access the MSaaS web portal:
#    http://<DOCKERHOST>:9876
# and the Docker Compose UI and Portainer UI can be accessed from the tabs.
#  
# (Weave and WeaveScope left out of this but should be running)  

services:
 nginx:
   image: nginx
   ports:
   - "9876:80"
   volumes:
   # Adapt this to the msaas portal html code location:
   -  /home/ubuntu/demo/aws/public_html/:/usr/share/nginx/html:ro
   #- /home/ubuntu/msaas-A/codebase/nginx/default.conf:/etc/nginx/conf.d/default.conf
   
 compose:
   image: francescou/docker-compose-ui:1.7.0
   ports:
    - 5000:5000
   #working_dir: /opt/docker-compose-projects/
   working_dir: /home/ubuntu/exercises
   volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    #- /var/run/weave/weave.sock:/var/run/docker.sock
    # Adapt thise volumes to your own environment:
    - /home/ubuntu/demo/exercises:/home/ubuntu/exercises
    - /home/ubuntu/demo/compose-ui/images:/app/static/images
    - /home/ubuntu/demo/compose-ui/index.html:/app/static/index.html 
    
 portainer:
  image: portainer/portainer
  ports:
   - "9000:9000"  
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
