version: '2'

# Docker composefile to start weavescope
# To be started on all nodes 1-5
 
services:
 scope:
  image: weaveworks/scope
  command: --probe.docker=true 172.31.47.67 172.31.39.130 172.31.36.168 172.31.42.74 172.31.42.76
  container_name: weavescope
  network_mode: "host"
  pid: "host"
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  restart: always 