version: '2'
 
# Docker compose file for Docker Swarm image.
# To join cluster

services:
 swarm:
  image: swarm
  command: join "nodes://172.31.36.168:2375,172.31.47.67:2375,172.31.42.76:2375,172.31.42.74:2375"
  restart: always